// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM6o1UI55_Phd0_XnQ4BXNgqY6tt_vNBY',
    appId: '1:187179912587:web:9fc24e8536b13e3590b38e',
    messagingSenderId: '187179912587',
    projectId: 'recetias-prueba-flutter',
    authDomain: 'recetias-prueba-flutter.firebaseapp.com',
    storageBucket: 'recetias-prueba-flutter.firebasestorage.app',
    measurementId: 'G-9308M2TR10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_0HEDFbjf2ehbWRXTlWuBo8jek76RPuI',
    appId: '1:187179912587:android:5ddd227c482c70ea90b38e',
    messagingSenderId: '187179912587',
    projectId: 'recetias-prueba-flutter',
    storageBucket: 'recetias-prueba-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApjF8pLFsoQbvbpk5STWapHiXte2O45V8',
    appId: '1:187179912587:ios:2ecbe666a7a5d36090b38e',
    messagingSenderId: '187179912587',
    projectId: 'recetias-prueba-flutter',
    storageBucket: 'recetias-prueba-flutter.firebasestorage.app',
    iosClientId: '187179912587-v6prf1arunvj4pk8983tfol92kupver8.apps.googleusercontent.com',
    iosBundleId: 'com.example.recetias2App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApjF8pLFsoQbvbpk5STWapHiXte2O45V8',
    appId: '1:187179912587:ios:2ecbe666a7a5d36090b38e',
    messagingSenderId: '187179912587',
    projectId: 'recetias-prueba-flutter',
    storageBucket: 'recetias-prueba-flutter.firebasestorage.app',
    iosClientId: '187179912587-v6prf1arunvj4pk8983tfol92kupver8.apps.googleusercontent.com',
    iosBundleId: 'com.example.recetias2App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM6o1UI55_Phd0_XnQ4BXNgqY6tt_vNBY',
    appId: '1:187179912587:web:f57ec7cd94b7715d90b38e',
    messagingSenderId: '187179912587',
    projectId: 'recetias-prueba-flutter',
    authDomain: 'recetias-prueba-flutter.firebaseapp.com',
    storageBucket: 'recetias-prueba-flutter.firebasestorage.app',
    measurementId: 'G-QRXRTD2S2L',
  );
}
